<?xml version="1.0"?>
<robot name="hdt_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- constants -->
    <xacro:property name="M_PI" value="3.1415926535897931"/>

    <xacro:property name="drive_length" value="0.047"/>
    <xacro:property name="a35_length" value="0.03855"/>
    
    <!--xacro:property name="drive_offset" value="0.033"/-->
    <xacro:property name="tube_diameter" value="0.0515"/>
    <xacro:property name="pedestal_height" value="0.03859"/>
    <xacro:property name="pedestal_boss" value="0.0448"/>
    <xacro:property name="drive_offset" value="0.02455"/>
    <xacro:property name="pincer_offset" value="0.0415"/>
    
    <xacro:property name="a24_proximal_length" value="0.353"/>
    <xacro:property name="a24_distal_length" value="0.344"/>
    <xacro:property name="a35_proximal_length" value="0.308"/>
    <xacro:property name="a35_distal_length" value="0.19"/>
    
    <!-- materials -->
    <material name="black">
        <color rgba="${200/255} ${200/255} ${200/255} 1.0"/>
    </material>

    <material name="grey">
        <color rgba="${64/255} ${64/255} ${64/255} 1.0"/>
    </material>
    
    <material name="yellow">
        <color rgba="${240/255} ${224/255} ${64/255} 1.0"/>
    </material>

     <!-- default inertia -->
     <xacro:macro name="default_inertia">
           <inertia
           ixx="0.005" ixy="0.0" ixz="0.0"
           iyy="0.005" iyz="0.0"
           izz="0.005"/>
     </xacro:macro>

    <!-- segment 0 -->
    <link name="base_link"/>

    <!-- pedestal -->
    <joint name="pedestal_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="pedestal_link"/>
    </joint>

    <link name="pedestal_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H026994 - A35 M-2 PEDESTAL ASSY - SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H026994 - A35 M-2 PEDESTAL ASSY - SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- drive 1 -->
    <joint name="drive1_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-2*M_PI}" upper="${2*M_PI}" velocity="${M_PI/4}"/>
        <origin xyz="0 0 ${(pedestal_boss+a35_length)}" rpy="0 0 ${-M_PI/2}"/>
        <parent link="pedestal_link"/>
        <child link="drive1_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive1_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- drive 2 -->
    <joint name="drive2_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-M_PI/2}" upper="${M_PI/2}" velocity="${M_PI/4}"/>
        <origin xyz="${drive_offset+drive_length} 0 0" rpy="0 -${M_PI/2} 0"/>
        <parent link="drive1_link"/>
        <child link="drive2_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive2_link">
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- humerus -->
    <joint name="humerus_joint" type="fixed">
        <origin xyz="${a35_proximal_length/2+drive_offset} 0 0" rpy="0 0 0" />
        <parent link="drive2_link"/>
        <child link="humerus_link"/>
    </joint>

    <link name="humerus_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024847 - A35 M-2 PROXIMAL TUBE ASSY - SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024847 - A35 M-2 PROXIMAL TUBE ASSY - SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- elbow -->
    <joint name="elbow_joint" type="fixed">
        <origin xyz="${a35_proximal_length/2+drive_offset} 0 0" rpy="0 0 0"/>
        <parent link="humerus_link"/>
        <child link="elbow_link"/>
    </joint>

    <link name="elbow_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
    
    <!-- drive 3 -->
    <joint name="drive3_joint" type="revolute">
        <axis xyz="0 0 1"/>
	<!-- position limits to match parameter settings on actuator -->
        <limit effort="60.0" lower="-4.49" upper="1.35" velocity="${M_PI/4}"/>
        <origin xyz="0 0 ${drive_length+drive_offset}" rpy="0 0 0"/>
        <parent link="elbow_link"/>
        <child link="drive3_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive3_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
 
     <!-- drive 4 -->
    <joint name="drive4_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-2*M_PI}" upper="${2*M_PI}" velocity="${M_PI/4}"/>
        <origin xyz="0 ${a35_distal_length/2 + drive_length} 0" rpy="-${M_PI/2} 0 0"/>
        <parent link="drive3_link"/>
        <child link="drive4_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive4_link">
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024848 - A35 M-2 DISTAL TUBE ASSY - SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024848 - A35 M-2 DISTAL TUBE ASSY - SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
    
    <!-- wrist -->
    <joint name="wrist_joint" type="fixed">
        <origin xyz="0 0 ${a35_distal_length/2 + drive_offset + 0.01}" rpy="${M_PI/2} -${M_PI/2} ${M_PI}"/>
        <parent link="drive4_link"/>
        <child link="wrist_link"/>
    </joint>

    <link name="wrist_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
    
     <!-- drive 5 -->
    <joint name="drive5_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-M_PI*2}" upper="${M_PI*2}" velocity="${M_PI/4}"/>
        <origin xyz="0 0 -${drive_length + drive_offset}" rpy="${M_PI} 0 0"/>
        <parent link="wrist_link"/>
        <child link="drive5_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive5_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

        <!-- drive 6 -->
    <joint name="drive6_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-M_PI*2}" upper="${M_PI*2}" velocity="${M_PI/4}"/>
        <origin xyz="${drive_length + pincer_offset} 0 0" rpy="0 ${M_PI/2} 0"/>
        <parent link="drive5_link"/>
        <child link="drive6_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive6_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024842 - A35 M-2 PINCER ASSY - SHAREABLE, UNDERWATER.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
            <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H024842 - A35 M-2 PINCER ASSY - SHAREABLE, UNDERWATER.STL"/>
            </geometry>
            <material name="black"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- endpoint -->
    <joint name="endpoint_joint" type="fixed">
        <origin xyz="0 0 0.1" rpy="${M_PI/2} ${-M_PI/2} 0"/> <!-- end effector offset can be added here -->
        <parent link="drive6_link"/>
        <child link="endpoint_link"/>
    </joint>

    <link name="endpoint_link">
    </link>
</robot>

